### ISSUE TITLE
hate과 offensive 차이

### ISSUE THREAD

**Issue by hash2430** [kocohub/korean-hate-speech#1]
안녕하세요
hate label에서 hate과 offensive 의 차이는 무엇인가요?
정도 차이인가요? 정도차이라면 offensive < hate 이런건가요?

**Comment by warnikchow** [comment]
안녕하세요. 말씀하신 대로, hate label의 경우 존재 유무보다는 정도와 가치판단의 문제에 가깝다고 저희도 생각하였고, 가이드라인에 역시 해당 내용이 반영되어 있습니다.

https://www.notion.so/c1ecb7cc52d446cc93d928d172ef8442

좀 더 자세히는, hate의 경우 기존에 정의되었던 혐오표현/모욕에 충분히 해당한다고 볼 수 있다고 생각되는 표현들 (특정한 아이덴티티에 기반하여 개인/그룹에 대한 적대감을 표출하거나 [혐오], 개인/그룹의 사회적 체면을 심각하게 손상할 수 있는 [모욕]) 에 대해서 hate의 레이블을 배정하였습니다. 또,  읽었을 때 기분이 나쁘지만 (혹은 글의 대상에게 기분나쁠 수 있지만) hate/insulting 정도는 아니라고 생각되는 표현들에 대해 offensive의 레이블을 매길 수 있도록 하였습니다. 

최종 레이블은 3인 annotator의 majority voting을 통해 결정하였으며, 결정이 voting으로 불가능한 경우라든지, hate/none으로 표가 갈리는 경우들에 대해서는 추가적인 회의로 최종 결정을 진행하였습니다. 따라서 사람마다 이것이 hate인지 offensive인지에 대한 시각이 조금씩은 다를 수 있다는 것을 말씀드립니다.
