### ISSUE TITLE
kaggle 제출 때 csv 관련

### ISSUE THREAD

**Issue by hash2430** [kocohub/korean-hate-speech#2]
안녕하세요
같은 방법으로 csv를 만들어도 gender bias detection은 통과하고
나머지 두개 competetion은 통과를 안하는데 제가 육안으로 csv를 봐서는 무슨 문제인지 모르겠어서요.
pandas와 csv 라이브러리 둘 다 시도해봤는데 gender bias detection만 통과하기는 마찬가지에요.
다음과 같은 에러가 나네요
"Evaluation Exception: Input string was not in a correct format."

**Comment by moon1ite** [comment]
@hash2430 

안녕하세요 :) Kaggle competition에 관심을 가져주셔서 감사합니다!
Kaggle 플랫폼 상에서 macro-F1-score 를 구하기 위해서는 `0, 1, 2`의 예측 결과가 명시적으로 integer 이어야 합니다 ㅎㅎ

ref: https://www.kaggle.com/c/costa-rican-household-poverty-prediction/discussion/61403
![image](https://user-images.githubusercontent.com/24843996/84027403-e395fe00-a9c9-11ea-9172-18151f10cfd4.png)

**Comment by hash2430** [comment]
감사합니다~~~

**Comment by sjkoo1989** [comment]
저도 비슷한 문제를 겪고 있는 것 같습니다.

kaggle page에는 label을 string 형태로 (none, offensive, hate) 등을 출력하도록 되어있는데,
위에 두분이서 나눈 대화는 label이 int형태로 주어져야 하는 것 처럼 보입니다.

혹시 샘플 submission file을 올려주실 수 있겠습니까?
아울러 어느 라벨이 몇 번 index에 대응되는지도 같이 kaggle에 알림을 받았으면 합니다.
